# Generated by Django 5.2.12 on 2026-03-23 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='dataAdded',
            new_name='dateAdded',
        ),
    ]
