# Generated by Django 5.2.12 on 2026-03-28 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grades',
            unique_together={('student', 'subject')},
        ),
    ]
